"""Type stub for the `_aeroelast` PyO3 extension.

`_aeroelast` is the compiled Rust extension that `maturin develop` installs into
the active environment. It ships no `.pyi`, so a type checker resolves the
`.so` as a module with no statically knowable members and reports every
`from _aeroelast import X` as an unknown symbol -- six test modules import from
it, plus `src/aeroelast/solvers` and `src/aeroelast/models`. This stub is the
repo's declaration of that surface, and `[tool.pyright] stubPath` in
`pyproject.toml` points the checker here.

The signatures are deliberately loose (`Any` in, `Any` out): the extension's
real signatures live in `crates/aeroelast-py/src/*.rs`, the tests exercise them
at runtime, and duplicating them here would only add a second copy to keep in
sync. What this stub buys is that the names resolve and that a typo in an
import is still caught.

Keep the symbol list in sync with `crates/aeroelast-py/src/lib.rs`'s
`add_function`/`add_class` calls.
"""

from typing import Any

class _Loose:
    """Base for the extension's classes: any attribute, any call."""

    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class ElementFamily(_Loose): ...
class IsotropicMaterial(_Loose): ...
class Laminate(_Loose): ...
class OrthotropicMaterial(_Loose): ...
class Ply(_Loose): ...
class PyMeshAssembler(_Loose): ...

def batch_fint_mitc3(*args: Any, **kwargs: Any) -> Any: ...
def batch_fint_mitc4(*args: Any, **kwargs: Any) -> Any: ...
def batch_ke_mitc3(*args: Any, **kwargs: Any) -> Any: ...
def batch_ke_mitc3_composite(*args: Any, **kwargs: Any) -> Any: ...
def batch_ke_mitc4(*args: Any, **kwargs: Any) -> Any: ...
def batch_ke_mitc4_composite(*args: Any, **kwargs: Any) -> Any: ...
def batch_kt_mitc3(*args: Any, **kwargs: Any) -> Any: ...
def batch_kt_mitc4(*args: Any, **kwargs: Any) -> Any: ...
def batch_me_mitc3(*args: Any, **kwargs: Any) -> Any: ...
def batch_me_mitc3_composite(*args: Any, **kwargs: Any) -> Any: ...
def batch_me_mitc4(*args: Any, **kwargs: Any) -> Any: ...
def batch_me_mitc4_composite(*args: Any, **kwargs: Any) -> Any: ...
def compute_rayleigh_auto(*args: Any, **kwargs: Any) -> Any: ...
def linear_static_solve_coo(*args: Any, **kwargs: Any) -> Any: ...
def modal_solve_coo(*args: Any, **kwargs: Any) -> Any: ...
def nonlinear_static_solve_coo(*args: Any, **kwargs: Any) -> Any: ...
def petsc_assemble_matrix(*args: Any, **kwargs: Any) -> Any: ...
def petsc_modal_solve(*args: Any, **kwargs: Any) -> Any: ...
def run_fsi_solver(*args: Any, **kwargs: Any) -> Any: ...
def run_rotor_fsi_solver(*args: Any, **kwargs: Any) -> Any: ...
def run_stress_stiffened_fsi_solver(*args: Any, **kwargs: Any) -> Any: ...
