"""The CalculiX ``DynamicFSI`` deck used by the preCICE adapter.

The CalculiX-preCICE adapter reuses CalculiX's point-force data structures for
the coupling interface, so the deck must load *every* node of the FSI interface
node set in *every* spatial direction: "it is necessary to load all nodes of
the node set, which defines the FSI interface in CalculiX, in each spatial
direction ... the values of these initial forces can (and should) be chosen to
zero" (calculix-adapter ``docs/configure.md``).  The adapter also drives a
``*DYNAMIC`` step, and the standard adapter deck looks like::

    *STEP, NLGEOM, INC=1000000
    *DYNAMIC
     0.01, 5.0
    *BOUNDARY
    *CLOAD
     Ninterface, 1, 0.0
     Ninterface, 2, 0.0
     Ninterface, 3, 0.0

``write_ccx_mesh`` grew a ``DynamicFSI`` solver-type branch that emits exactly
that deck (plus an optional per-material Rayleigh ``*DAMPING`` card).  This
module pins the emitted cards, the argument validation, and -- as a regression
guard -- that the pre-existing ``Modal`` and ``LinearStatic`` decks are
byte-identical to the output captured *before* the branch existed.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from tests.conftest import ccx_bin_or_skip

from aeroelast.core.material import IsotropicMaterial
from aeroelast.core.mesh.entities import ElementSet, ElementType, MeshElement, Node, NodeSet
from aeroelast.core.mesh.io.writers import write_ccx_mesh
from aeroelast.core.mesh.model import MeshModel
from aeroelast.core.properties import ShellProperty

from tests.support.ccx_io import parse_frd_disp, run_ccx

STEEL = IsotropicMaterial(name="STEEL", E=2.1e11, nu=0.3, rho=7800.0)
ALUMINIUM = IsotropicMaterial(name="ALUMINIUM", E=7.0e10, nu=0.33, rho=2700.0)
THICKNESS = 0.01

#: FSI interface node-set name passed without the writer's ``N`` prefix; the
#: writer uppercases and prefixes it, exactly like ``load_nodeset``.
INTERFACE = "allOuterShellNods"
INTERFACE_SET = "NALLOUTERSHELLNODS"  # writer-emitted label
BOUNDARY_SET = "NCLAMPED"

# ---------------------------------------------------------------------------
# Pre-change golden decks (captured from the writer before the DynamicFSI
# branch was added).  Any diff here means an existing solver type changed.
# ---------------------------------------------------------------------------

GOLDEN_MODAL_INP = """\
**
** CalculiX input file generated by aeroelast
** Following CGX file structure conventions
**
** ===========================================
**              MESH DEFINITION
** ===========================================
**
*INCLUDE, INPUT=modal.msh
**
** ===========================================
**         NODE AND ELEMENT SETS
** ===========================================
**
*INCLUDE, INPUT=modal.nam
**
** ===========================================
**           MATERIAL DEFINITIONS
** ===========================================
**
*MATERIAL, NAME=STEEL
*ELASTIC
2.100000E+11, 0.300000
*DENSITY
7.800000E+03
**
** ===========================================
**           SECTION DEFINITIONS
** ===========================================
**
*SHELL SECTION, ELSET=EPLATE, MATERIAL=STEEL
1.000000E-02
**
** ===========================================
**          BOUNDARY CONDITIONS
** ===========================================
**
*BOUNDARY
NCLAMPED, 1, 6, 0.0
**
** ===========================================
**              MODAL ANALYSIS
** ===========================================
**
*STEP
*FREQUENCY
5
**
*NODE FILE, OUTPUT=2D
U
*EL FILE, OUTPUT=2D
S, E
**
*END STEP
"""

GOLDEN_STATIC_INP = """\
**
** CalculiX input file generated by aeroelast
** Following CGX file structure conventions
**
** ===========================================
**              MESH DEFINITION
** ===========================================
**
*INCLUDE, INPUT=static.msh
**
** ===========================================
**         NODE AND ELEMENT SETS
** ===========================================
**
*INCLUDE, INPUT=static.nam
**
** ===========================================
**           MATERIAL DEFINITIONS
** ===========================================
**
*MATERIAL, NAME=STEEL
*ELASTIC
2.100000E+11, 0.300000
*DENSITY
7.800000E+03
**
** ===========================================
**           SECTION DEFINITIONS
** ===========================================
**
*SHELL SECTION, ELSET=EPLATE, MATERIAL=STEEL
1.000000E-02
**
** ===========================================
**          BOUNDARY CONDITIONS
** ===========================================
**
*BOUNDARY
NCLAMPED, 1, 6, 0.0
**
** ===========================================
**           LINEAR STATIC ANALYSIS
** ===========================================
**
*STEP
*STATIC
**
*CLOAD
NALLOUTERSHELLNODS, 3, 3.333333E+01
**
*NODE FILE, OUTPUT=2D
U, RF
*EL FILE, OUTPUT=2D
S, E
**
*END STEP
"""


# ---------------------------------------------------------------------------
# Small 2x2 quad shell mesh (mirrors tests/test_ccx_writer_ids.py)
# ---------------------------------------------------------------------------


def _build_mesh(*, split_elements: bool = False) -> MeshModel:
    """A 2x2 quad plate strip with a clamped edge and an interface edge."""
    Node._id_counter = 0
    MeshElement._id_counter = 0

    mesh = MeshModel()
    grid: dict[tuple[int, int], Node] = {}
    for j in range(3):
        for i in range(3):
            node = Node([float(i), float(j), 0.0], geometric_node=False)
            mesh.add_node(node)
            grid[(i, j)] = node

    elements: list[MeshElement] = []
    for j in range(2):
        for i in range(2):
            element = MeshElement(
                nodes=[grid[(i, j)], grid[(i + 1, j)], grid[(i + 1, j + 1)], grid[(i, j + 1)]],
                element_type=ElementType.quad,
            )
            mesh.add_element(element)
            elements.append(element)

    mesh.add_node_set(NodeSet("clamped", {n for n in mesh.nodes if np.isclose(n.y, 0.0)}))
    mesh.add_node_set(NodeSet(INTERFACE, {n for n in mesh.nodes if np.isclose(n.y, 2.0)}))

    if split_elements:
        # Two element sets so two *MATERIAL blocks are emitted.
        mesh.add_element_set(ElementSet("plate_a", {elements[0]}))
        mesh.add_element_set(ElementSet("plate_b", set(elements[1:])))
    else:
        mesh.add_element_set(ElementSet("plate", set(mesh.elements)))
    return mesh


def _properties() -> dict:
    return {"plate": ShellProperty(material=STEEL, thickness=THICKNESS)}


def _write_fsi(tmp_path: Path, stem: str = "fsi", **kwargs) -> Path:
    inp = tmp_path / f"{stem}.inp"
    write_ccx_mesh(
        _build_mesh(),
        str(inp),
        properties=_properties(),
        boundary_nodeset="clamped",
        solver_type="DynamicFSI",
        fsi_interface_nodeset=INTERFACE,
        **kwargs,
    )
    return inp


# ---------------------------------------------------------------------------
# 1. Adapter step cards
# ---------------------------------------------------------------------------


def test_dynamic_fsi_deck_emits_adapter_cards(tmp_path: Path) -> None:
    """nlgeom/direct increments, the time line and the zero *CLOAD block."""
    inp = _write_fsi(tmp_path, nlgeom=True, direct_increments=True, dt=1e-2, t_end=0.02)
    text = inp.read_text()

    assert "*STEP, NLGEOM, INC=1000000" in text
    assert "*DYNAMIC, DIRECT" in text
    assert "1.000000E-02, 2.000000E-02" in text

    # One zero load line per spatial DOF, on the emitted (upper, N-prefixed) set.
    for dof in (1, 2, 3):
        assert f"{INTERFACE_SET}, {dof}, 0.0" in text
    assert text.count(f"{INTERFACE_SET}, ") == 3


def test_dynamic_fsi_output_frequency_default_and_override(tmp_path: Path) -> None:
    """Output requests default to the writer's ``FREQUENCY=10`` and honour an override."""
    default_text = _write_fsi(tmp_path, stem="fsi_default").read_text()
    assert "*NODE FILE, FREQUENCY=10" in default_text
    assert "*EL FILE, FREQUENCY=10" in default_text

    override_text = _write_fsi(tmp_path, stem="fsi_freq", output_frequency=1).read_text()
    assert "*NODE FILE, FREQUENCY=1" in override_text
    assert "*EL FILE, FREQUENCY=1" in override_text


# ---------------------------------------------------------------------------
# 2. Rayleigh damping inside every *MATERIAL block
# ---------------------------------------------------------------------------


def test_dynamic_fsi_rayleigh_damping_in_every_material(tmp_path: Path) -> None:
    inp = tmp_path / "fsi.inp"
    write_ccx_mesh(
        _build_mesh(split_elements=True),
        str(inp),
        properties={
            "plate_a": ShellProperty(material=STEEL, thickness=THICKNESS),
            "plate_b": ShellProperty(material=ALUMINIUM, thickness=THICKNESS),
        },
        boundary_nodeset="clamped",
        solver_type="DynamicFSI",
        fsi_interface_nodeset=INTERFACE,
        rayleigh_damping=(0.5, 1e-3),
    )
    text = inp.read_text()
    card = "*DAMPING, ALPHA=5.000000E-01, BETA=1.000000E-03"

    material_blocks = text.split("*MATERIAL")[1:]
    assert len(material_blocks) == 2, text
    for block in material_blocks:
        assert card in block
    assert text.count(card) == 2


def test_rayleigh_damping_not_emitted_for_other_solver_types(tmp_path: Path) -> None:
    """Other solver types must not gain a *DAMPING card from the new argument."""
    inp = tmp_path / "modal.inp"
    write_ccx_mesh(
        _build_mesh(),
        str(inp),
        properties=_properties(),
        boundary_nodeset="clamped",
        solver_type="Modal",
        num_modes=5,
        rayleigh_damping=(0.5, 1e-3),
    )
    assert "*DAMPING" not in inp.read_text()


# ---------------------------------------------------------------------------
# 3. Argument validation
# ---------------------------------------------------------------------------


def test_dynamic_fsi_requires_interface_nodeset(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="fsi_interface_nodeset"):
        write_ccx_mesh(
            _build_mesh(),
            str(tmp_path / "fsi.inp"),
            properties=_properties(),
            boundary_nodeset="clamped",
            solver_type="DynamicFSI",
        )


@pytest.mark.parametrize("bad", [(1.0,), (1.0, 2.0, 3.0), ("a", 1.0), 0.5])
def test_bad_rayleigh_damping_raises(tmp_path: Path, bad: object) -> None:
    with pytest.raises(ValueError, match="rayleigh_damping"):
        write_ccx_mesh(
            _build_mesh(),
            str(tmp_path / "fsi.inp"),
            properties=_properties(),
            boundary_nodeset="clamped",
            solver_type="DynamicFSI",
            fsi_interface_nodeset=INTERFACE,
            rayleigh_damping=bad,  # pyright: ignore[reportArgumentType] - deliberately invalid
        )


# ---------------------------------------------------------------------------
# 4. Regression: Modal / LinearStatic decks unchanged
# ---------------------------------------------------------------------------


def test_modal_deck_unchanged(tmp_path: Path) -> None:
    inp = tmp_path / "modal.inp"
    write_ccx_mesh(
        _build_mesh(),
        str(inp),
        properties=_properties(),
        boundary_nodeset="clamped",
        solver_type="Modal",
        num_modes=5,
    )
    assert inp.read_text() == GOLDEN_MODAL_INP


def test_linear_static_deck_unchanged(tmp_path: Path) -> None:
    inp = tmp_path / "static.inp"
    write_ccx_mesh(
        _build_mesh(),
        str(inp),
        properties=_properties(),
        boundary_nodeset="clamped",
        solver_type="LinearStatic",
        load_nodeset=INTERFACE,
        load_vector=[0.0, 0.0, 100.0],
    )
    assert inp.read_text() == GOLDEN_STATIC_INP


# ---------------------------------------------------------------------------
# 5. End-to-end CalculiX parse check
# ---------------------------------------------------------------------------


def _frd_node_numbers(frd_path: Path) -> list[int]:
    """Node numbers from the FRD nodal-coordinate (``2C``) block.

    Without ``OUTPUT=2D`` CalculiX expands a shell deck to its 3D counterpart
    for output, so the FRD node numbers do not equal the input mesh labels.
    Read them from the file instead of assuming a mapping.
    """
    numbers: list[int] = []
    in_nodes = False
    for line in frd_path.read_text().splitlines():
        if line.strip().startswith("2C"):
            in_nodes = True
            continue
        if in_nodes and line.startswith(" -3"):
            break
        if in_nodes and line.startswith(" -1"):
            numbers.append(int(line[3:13]))
    return numbers


def test_dynamic_fsi_deck_runs_in_ccx(tmp_path: Path) -> None:
    """The emitted deck must run in the real binary and write a DISP block."""
    ccx_bin = ccx_bin_or_skip()
    inp = tmp_path / "fsi.inp"
    write_ccx_mesh(
        _build_mesh(),
        str(inp),
        properties=_properties(),
        boundary_nodeset="clamped",
        solver_type="DynamicFSI",
        fsi_interface_nodeset=INTERFACE,
        dt=5e-3,
        t_end=1e-2,
    )

    completed = run_ccx(inp, ccx_bin)
    assert completed.returncode == 0, (
        f"ccx failed (rc={completed.returncode}):\n{completed.stdout[-2000:]}"
    )

    frd = inp.with_suffix(".frd")
    frd_nodes = _frd_node_numbers(frd)
    assert frd_nodes, f"no nodal block in {frd}"
    disp = parse_frd_disp(frd, frd_nodes)
    assert set(disp) == set(frd_nodes), (
        f"FRD has no complete DISP block: parsed {len(disp)} of {len(frd_nodes)} nodes"
    )
