"""A2 — Modal participation factors by direction (cierra F1: 2nd edgewise mode-swap).

Reproduces the V-02 modal setup (IEA 15 MW blade, NuMAD xlsx, element_size=0.25 m,
RCM renumber, clamped root) and exports the effective-mass participation matrix
shape (n_modes, n_rb_dirs) computed by ModalSolver. With dpn=6 (SHELL), the
columns are [Tx, Ty, Tz, Rx, Ry, Rz] in percent of total directional mass.

Lectura del modo en disputa (1.98 Hz):
  - Tx > 50% → 2nd edgewise puro (sesgo -8.65% real, promover a aserción cerrada).
  - Tx ~ Ty (~30-40% c/u, Rz no despreciable) → modo mixto flap-edge-tor; el "2nd
    edgewise" puro no existe en esta pala compuesta — comparación pierde sentido.
  - Ty > 50% → swap entre modos 4 y 5; buscar verdadero 2nd edgewise en otro autovalor.

Outputs:
  docs/validation_data/generated/v02_modal_participation.csv
  docs/validation_data/generated/v02_modal_participation_summary.md

Requires the GCC + PETSc/SLEPc + Rust extension runtime (module load gcc).
"""

from __future__ import annotations

import pathlib
import sys

import numpy as np


REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT_DIR = REPO_ROOT / "docs" / "validation_data" / "generated"
OUT_DIR.mkdir(parents=True, exist_ok=True)

BLADE_XLSX = REPO_ROOT / "tests" / "NuMAD_utd_iea15mw.xlsx"

NUM_MODES = 10
ELEMENT_SIZE = 0.25

# Reference frequencies from the IEA-15-240-RWT package (used only to label rows).
REF_LABELS = {
    "1st flapwise": 0.5585,
    "1st edgewise": 0.6406,
    "2nd flapwise": 1.6590,
    "2nd edgewise": 2.1670,
}


def closest_index(arr: np.ndarray, target: float) -> int:
    return int(np.argmin(np.abs(arr - target)))


def main() -> int:
    if not BLADE_XLSX.exists():
        print(f"ERROR: blade xlsx not found at {BLADE_XLSX}", file=sys.stderr)
        return 2

    from aeroelast.core.bc import DirichletCondition
    from aeroelast.core.mesh.generators import BladeMesh
    from aeroelast.elements import ElementFamily
    from aeroelast.models.blade.model import build_rust_properties
    from aeroelast.solvers.modal import ModalSolver

    print(f"[A2] Building blade mesh from {BLADE_XLSX.name} (element_size={ELEMENT_SIZE} m)...")
    generator = BladeMesh(
        excel_file=str(BLADE_XLSX),
        airfoil_dir=str(BLADE_XLSX.parent / "airfoils"),
        element_size=ELEMENT_SIZE,
    )
    mesh = generator.generate(renumber="rcm")
    properties = build_rust_properties(generator.numad_mesh_data)

    cfg = {
        "solver": {"num_modes": NUM_MODES},
        "elements": {
            "element_family": ElementFamily.SHELL,
            "span_direction": (0.0, 0.0, 1.0),
            "properties": properties,
        },
    }
    solver = ModalSolver(mesh, cfg)

    dpn = solver.domain.dofs_per_node
    print(f"[A2] dofs_per_node = {dpn} (expected 6 for SHELL).")

    # Clamp root (all 6 DOFs).
    root_node_ids = sorted(mesh.get_node_set("RootNodes").nodes.keys())
    node_id_to_idx = mesh.node_id_to_index
    root_dofs = sorted(
        node_id_to_idx[nid] * dpn + d for nid in root_node_ids for d in range(dpn)
    )
    solver.add_dirichlet_conditions([DirichletCondition(root_dofs, 0.0)])

    print(f"[A2] Solving modal problem ({NUM_MODES} modes)...")
    freqs_hz, _ = solver.solve()
    freqs_hz = np.asarray(freqs_hz)

    factors = np.asarray(solver.participation_factors)  # (n_modes, n_rb_dirs) in %
    n_modes, n_dirs = factors.shape
    print(f"[A2] Participation matrix shape: {factors.shape}")

    # Column labels — translational X/Y/Z first, rotational X/Y/Z if dpn≥6.
    direction_labels = ["Tx", "Ty", "Tz"][:min(dpn, 3)]
    if dpn >= 6:
        direction_labels += ["Rx", "Ry", "Rz"]
    direction_labels = direction_labels[:n_dirs]

    # Export CSV: first column = mode index (1..N), second = frequency, rest = % per direction.
    header = "mode,freq_hz," + ",".join(direction_labels)
    rows = np.column_stack([np.arange(1, n_modes + 1), freqs_hz, factors])
    csv_path = OUT_DIR / "v02_modal_participation.csv"
    np.savetxt(
        csv_path,
        rows,
        header=header,
        delimiter=",",
        comments="",
        fmt=["%d", "%.6f"] + ["%.4f"] * n_dirs,
    )
    print(f"[A2] Wrote {csv_path}")

    # Build Markdown summary with reference-mode lookup.
    md_lines = [
        "# V-02 Modal participation factors — auto-generated by A2 script",
        "",
        f"Source: IEA 15 MW blade ({BLADE_XLSX.name}), element_size={ELEMENT_SIZE} m, RCM, clamped root.",
        f"Solver: ModalSolver (PETSc + SLEPc via Rust). num_modes={NUM_MODES}.",
        "",
        "## Effective mass participation by direction (%)",
        "",
        "Convention: span direction = global Z (axial). Therefore Tx = edgewise translation,",
        "Ty = flapwise translation, Tz = axial; Rx/Ry = section-bending rotations; Rz = torsion around span.",
        "",
        "| Mode | f [Hz] | " + " | ".join(direction_labels) + " |",
        "|---:|---:|" + "---:|" * n_dirs,
    ]
    for i in range(n_modes):
        row = "| " + str(i + 1) + " | " + f"{freqs_hz[i]:.4f}" + " | "
        row += " | ".join(f"{factors[i, d]:.2f}" for d in range(n_dirs))
        row += " |"
        md_lines.append(row)

    md_lines.append("")
    md_lines.append("## Mode-swap diagnostic — modes closest to reference frequencies")
    md_lines.append("")
    md_lines.append(
        "For each reference mode, report the AeroElast eigenvalue closest to its frequency "
        "and the dominant direction(s) of that eigenvector."
    )
    md_lines.append("")
    md_lines.append("| Reference | f_ref [Hz] | Closest AeroElast f [Hz] | Dominant direction(s) | Lectura |")
    md_lines.append("|---|---:|---:|---|---|")

    for label, f_ref in REF_LABELS.items():
        idx = closest_index(freqs_hz, f_ref)
        dom_dir = direction_labels[int(np.argmax(factors[idx]))]
        # Identify any other direction above 20% (mixed-mode flag).
        secondary = [
            direction_labels[d]
            for d in range(n_dirs)
            if d != int(np.argmax(factors[idx])) and factors[idx, d] > 20.0
        ]
        if not secondary:
            reading = f"Modo {label.split()[0]}-dominant ({dom_dir}); identificación cerrada."
        else:
            mixed = ", ".join(secondary)
            reading = (
                f"Modo MIXTO: dominante {dom_dir} pero {mixed} > 20%. "
                "Comparación punto-a-punto vs referencia puede no ser apples-to-apples."
            )
        md_lines.append(
            f"| {label} | {f_ref:.4f} | {freqs_hz[idx]:.4f} | "
            f"{dom_dir} ({factors[idx, int(np.argmax(factors[idx]))]:.1f}%) | {reading} |"
        )

    md_lines.append("")
    md_lines.append("## Closing note for §5.2 (2nd edgewise mode-swap)")
    md_lines.append("")
    idx_2nd_edge = closest_index(freqs_hz, REF_LABELS["2nd edgewise"])
    f_2nd_edge = freqs_hz[idx_2nd_edge]
    p_tx = factors[idx_2nd_edge, 0]
    p_ty = factors[idx_2nd_edge, 1]
    md_lines.append(
        f"AeroElast mode {idx_2nd_edge + 1} at f = {f_2nd_edge:.4f} Hz "
        f"has Tx = {p_tx:.1f}% and Ty = {p_ty:.1f}%."
    )
    md_lines.append("")
    # Heuristic: compare Tx vs Ty by RATIO, not absolute difference, because
    # for higher modes the absolute participation is small for everyone.
    # A "mixed" mode requires Ty to be at least ~30% of Tx (not just present).
    eps = 1e-6
    ratio_tx_over_ty = p_tx / max(p_ty, eps)
    ratio_ty_over_tx = p_ty / max(p_tx, eps)
    md_lines.append("Interpretación según ratio Tx/Ty:")
    md_lines.append("")
    md_lines.append(f"- Ratio Tx/Ty = {ratio_tx_over_ty:.2f} (Ty/Tx = {ratio_ty_over_tx:.2f}).")
    md_lines.append("")
    if ratio_tx_over_ty > 3 and p_tx > 2:
        md_lines.append(
            "- **Edge puro** — Tx domina claramente sobre Ty. El sesgo -8.65% vs "
            "IEA-15-240-RWT es real y promovible a aserción cerrada. La dispersión "
            "multi-método ±15% del campo lo cubre."
        )
    elif ratio_ty_over_tx > 3 and p_ty > 2:
        md_lines.append(
            "- **Mode SWAP** — el modo en ~1.98 Hz es 2do flap, no edge. Buscar el "
            "verdadero 2do edgewise en autovalores vecinos (modos 3-6 ordenados por Tx %)."
        )
    elif p_tx > 2 and p_ty > 2:
        md_lines.append(
            "- **Modo MIXTO flap-edge** — ambas componentes traslacionales tienen "
            "participación comparable. El 'segundo edgewise puro' no existe como objeto "
            "físico en esta pala compuesta. Recomendación: retirar del comparativo y "
            "reportar como mode-coupling propio del modelo shell."
        )
    else:
        md_lines.append(
            "- **Modo con participación traslacional baja** — interpretar con cautela; "
            "revisar la tabla completa (puede ser modo torsional puro si Rz domina)."
        )

    md_path = OUT_DIR / "v02_modal_participation_summary.md"
    md_path.write_text("\n".join(md_lines) + "\n")
    print(f"[A2] Wrote {md_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
